name: Trigger Docker Hub build

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install HTTPie
      run: sudo apt-get install httpie

    - name: Send request to Docker Hub to trigger a build
      run: >
        http post https://hub.docker.com/api/build/v1/source/83564f19-c21a-4dae-9690-971aee3b2a3b/trigger/6a6767a6-7d0d-4050-9055-958552e53b98/call/'
